# -*- coding: utf-8 -*-
"""GRAPH

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ug5l14q6ILjcT89ziMriPY4UbI8AAS2l

Tugas 1 — Graf Baru dengan 5 Simpul dan 7 Sisi
"""

from collections import deque

# Definisi fungsi print_graph
def print_graph(graph):
    for node in graph:
        print(f"{node} -> {graph[node]}")

# Definisi fungsi BFS
def bfs(graph, start):
    visited = set()
    queue = deque([start])
    while queue:
        vertex = queue.popleft()
        if vertex not in visited:
            print(vertex, end=' ')
            visited.add(vertex)
            queue.extend([n for n in graph[vertex] if n not in visited])

# Definisi fungsi DFS
def dfs(graph, start, visited=None):
    if visited is None:
        visited = set()
    if start not in visited:
        print(start, end=' ')
        visited.add(start)
        for neighbor in graph[start]:
            dfs(graph, neighbor, visited)
kota_graph = {
    'Jakarta':  ['Bogor', 'Bandung', 'Semarang'],
    'Bogor':    ['Jakarta', 'Bandung'],
    'Bandung':  ['Jakarta', 'Bogor', 'Yogyakarta'],
    'Semarang': ['Jakarta', 'Yogyakarta'],
    'Yogyakarta': ['Bandung', 'Semarang']
}

print_graph(kota_graph)

"""Tugas 2 — BFS dan DFS dari Simpul Pilihan"""

from collections import deque

# Definisi fungsi print_graph
def print_graph(graph):
    for node in graph:
        print(f"{node} -> {graph[node]}")

# Definisi fungsi BFS
def bfs(graph, start):
    visited = set()
    queue = deque([start])
    while queue:
        vertex = queue.popleft()
        if vertex not in visited:
            print(vertex, end=' ')
            visited.add(vertex)
            queue.extend([n for n in graph[vertex] if n not in visited])

# Definisi fungsi DFS
def dfs(graph, start, visited=None):
    if visited is None:
        visited = set()
    if start not in visited:
        print(start, end=' ')
        visited.add(start)
        for neighbor in graph[start]:
            dfs(graph, neighbor, visited)
print("BFS dari Jakarta:")
bfs(kota_graph, 'Jakarta')
# Output: Jakarta Bogor Bandung Semarang Yogyakarta

print("\nDFS dari Jakarta:")
dfs(kota_graph, 'Jakarta')

"""Tugas 3 — BFS yang Mengembalikan List Urutan Kunjungan"""

from collections import deque

# Definisi fungsi print_graph
def print_graph(graph):
    for node in graph:
        print(f"{node} -> {graph[node]}")

# Definisi fungsi BFS
def bfs(graph, start):
    visited = set()
    queue = deque([start])
    while queue:
        vertex = queue.popleft()
        if vertex not in visited:
            print(vertex, end=' ')
            visited.add(vertex)
            queue.extend([n for n in graph[vertex] if n not in visited])

# Definisi fungsi DFS
def dfs(graph, start, visited=None):
    if visited is None:
        visited = set()
    if start not in visited:
        print(start, end=' ')
        visited.add(start)
        for neighbor in graph[start]:
            dfs(graph, neighbor, visited)
from collections import deque

def bfs_return(graph, start):
    visited = set()
    queue = deque([start])
    order = []

    while queue:
        vertex = queue.popleft()
        if vertex not in visited:
            order.append(vertex)
            visited.add(vertex)
            queue.extend([
                n for n in graph[vertex]
                if n not in visited
            ])
    return order

hasil = bfs_return(kota_graph, 'Jakarta')
print(hasil)

"""Tugas 4 — Fungsi find_path dengan DFS"""

def find_path(graph, start, end, visited=None, path=None):
    if visited is None:
        visited = set()
    if path is None:
        path = []

    visited.add(start)
    path = path + [start]

    if start == end:
        return path

    for neighbor in graph[start]:
        if neighbor not in visited:
            result = find_path(graph, neighbor, end, visited, path)
            if result is not None:
                return result
    return None

jalur = find_path(kota_graph, 'Jakarta', 'Yogyakarta')
print(jalur)

"""Tugas 5 — Fungsi is_connected dengan DFS"""

def is_connected(graph):
    if not graph:
        return True

    start = next(iter(graph))  # Ambil simpul pertama
    visited = set()

    def dfs_helper(node):
        visited.add(node)
        for neighbor in graph[node]:
            if neighbor not in visited:
                dfs_helper(neighbor)

    dfs_helper(start)
    return len(visited) == len(graph)

print(is_connected(kota_graph))
# Output: True  (semua simpul terhubung)

# Pengujian dengan graf tidak terhubung:
disconnected = {
    'A': ['B'], 'B': ['A'],
    'C': ['D'], 'D': ['C']  # Komponen terpisah
}
print(is_connected(disconnected))