# -*- coding: utf-8 -*-
"""Modul 6 Zhio-0063.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jMNWPa6ONYah_IdWbhdtdzU1CxDmvSbI

Bubble Sort
"""

def bubble_sort(arr):
    n = len(arr)
    # Melakukan iterasi sebanyak jumlah elemen
    for i in range(n - 1):
        # Membandingkan elemen bersebelahan
        for j in range(n - i - 1):
            if arr[j] > arr[j + 1]:
                # Tukar posisi jika elemen kiri lebih besar dari kanan
                arr[j], arr[j + 1] = arr[j + 1], arr[j]
    return arr

# Contoh penggunaan
data = [64, 34, 25, 12, 22, 11, 90]
print("Data sebelum sorting:", data)
print("Data setelah Bubble Sort:", bubble_sort(data.copy()))

"""Selection Sort"""

def selection_sort(arr):
    n = len(arr)
    for i in range(n):
        # Menganggap elemen saat ini sebagai yang terkecil
        min_index = i
        for j in range(i + 1, n):
            # Mencari elemen yang lebih kecil di sisa daftar
            if arr[j] < arr[min_index]:
                min_index = j
        # Tukar elemen terkecil yang ditemukan ke posisi i
        arr[i], arr[min_index] = arr[min_index], arr[i]
    return arr

# Contoh penggunaan
data = [64, 25, 12, 22, 11]
print("Data setelah Selection Sort:", selection_sort(data.copy()))

"""Insertion Sort"""

def insertion_sort(arr):
    n = len(arr)
    for i in range(1, n):
        key = arr[i] # Elemen yang akan disisipkan
        j = i - 1
        # Geser elemen yang lebih besar dari 'key' ke arah kanan
        while j >= 0 and arr[j] > key:
            arr[j + 1] = arr[j]
            j -= 1
        # Tempatkan 'key' di posisi kosong yang benar
        arr[j + 1] = key
    return arr

# Contoh penggunaan
data = [64, 34, 25, 12, 22, 11, 90]
print("Data setelah Insertion Sort:", insertion_sort(data.copy()))

"""Merge Sort"""

def merge_sort(arr):
    if len(arr) > 1:
        mid = len(arr) // 2
        left_half = arr[:mid]
        right_half = arr[mid:]

        # Pecah terus secara rekursif
        merge_sort(left_half)
        merge_sort(right_half)

        # Proses penggabungan (merging)
        i = j = k = 0
        while i < len(left_half) and j < len(right_half):
            if left_half[i] < right_half[j]:
                arr[k] = left_half[i]
                i += 1
            else:
                arr[k] = right_half[j]
                j += 1
            k += 1

        # Pastikan tidak ada elemen yang tertinggal
        while i < len(left_half):
            arr[k] = left_half[i]
            i += 1
            k += 1
        while j < len(right_half):
            arr[k] = right_half[j]
            j += 1
            k += 1
    return arr

# Contoh penggunaan
data = [64, 25, 12, 22, 11]
print("Data setelah Merge Sort:", merge_sort(data.copy()))

"""Quick Sort"""

def quick_sort(arr):
    if len(arr) <= 1:
        return arr

    # Pilih pivot (di sini menggunakan elemen tengah)
    pivot = arr[len(arr) // 2]

    # Kelompokkan elemen
    left = [x for x in arr if x < pivot]    # Lebih kecil
    middle = [x for x in arr if x == pivot] # Sama dengan pivot
    right = [x for x in arr if x > pivot]   # Lebih besar

    # Gabungkan secara rekursif
    return quick_sort(left) + middle + quick_sort(right)

# Contoh penggunaan
data = [64, 25, 12, 22, 11]
print("Data setelah Quick Sort:", quick_sort(data.copy()))

"""Tugas MODUL6 Rombel 4"""

def urutkan_rating(film):
    for i in range(1, len(film)):
        kunci = film[i]
        j = i - 1
        # Geser film yang ratingnya lebih rendah ke belakang
        while j >= 0 and film[j]['rating'] < kunci['rating']:
            film[j + 1] = film[j]
            j -= 1
        film[j + 1] = kunci
    return film

# Data Film
movies = [
    {'judul': 'Film Agak Lain', 'rating': 4.2},
    {'judul': 'Film Interstelar', 'rating': 4.8},
    {'judul': 'Film Upin Ipin The Movie', 'rating': 4.5}
]

print("Rekomendasi Film (Rating Tinggi):", urutkan_rating(movies))