# -*- coding: utf-8 -*-
"""MODUL 9: HASHING

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lV8NWVvQwK0IdXsdZS8vqINF4hwVtoft
"""

# 1. Hash Table Sederhana (Tanpa Penanganan Collision)
class SimpleHashTable:
    def __init__(self, size):
        self.size = size
        self.table = [None] * size

    def hash_function(self, key):
        return hash(key) % self.size

    def insert(self, key, value):
        index = self.hash_function(key)
        self.table[index] = value

    def search(self, key):
        index = self.hash_function(key)
        return self.table[index]

# 2. Hash Table dengan Linear Probing
class LinearProbingHashTable:
    def __init__(self, size):
        self.size = size
        self.table = [None] * size

    def hash_function(self, key):
        return hash(key) % self.size

    def insert(self, key, value):
        index = self.hash_function(key)
        original_index = index

        while self.table[index] is not None:
            if self.table[index][0] == key:
                break
            index = (index + 1) % self.size
            if index == original_index:
                raise Exception("Hash table penuh")

        self.table[index] = (key, value)

    def search(self, key):
        index = self.hash_function(key)
        original_index = index

        while self.table[index] is not None:
            if self.table[index][0] == key:
                return self.table[index][1]
            index = (index + 1) % self.size
            if index == original_index:
                break

        return None

# 3. Hash Table dengan Chaining
class ChainingHashTable:
    def __init__(self, size):
        self.size = size
        self.table = [[] for _ in range(size)]

    def hash_function(self, key):
        return hash(key) % self.size

    def insert(self, key, value):
        index = self.hash_function(key)

        for i, (k, v) in enumerate(self.table[index]):
            if k == key:
                self.table[index][i] = (key, value)
                return
        self.table[index].append((key, value))

    def search(self, key):
        index = self.hash_function(key)
        for k, v in self.table[index]:
            if k == key:
                return v
        return None


# PENYELESAIAN TUGAS PRAKTIKUM

print("=== CONTOH SIMPLE HASH TABLE ===")
ht_simple = SimpleHashTable(10)
ht_simple.insert("apel", 100)
ht_simple.insert("pisang", 200)
print("Nilai untuk 'apel':", ht_simple.search("apel"))
print("Nilai untuk 'pisang':", ht_simple.search("pisang"))
print("\n")


print("=== TUGAS 1: LINEAR PROBING ===")
# Inisialisasi tabel ukuran 5
ht_linear = LinearProbingHashTable(5)

# Memasukkan data sesuai instruksi
ht_linear.insert("A", 10)
ht_linear.insert("B", 20)
ht_linear.insert("C", 30)
ht_linear.insert("D", 40)
ht_linear.insert("E", 50)

print("Isi tabel Linear Probing:")
print(ht_linear.table)
print("\n")


print("=== TUGAS 2: CHAINING ===")
# Inisialisasi tabel ukuran 3
ht_chaining = ChainingHashTable(3)

# Memasukkan data buah-buahan
ht_chaining.insert("apel", 100)
ht_chaining.insert("melon", 200)
ht_chaining.insert("lemon", 300)
ht_chaining.insert("pisang", 400)

print("Isi tabel Chaining:")
for i, slot in enumerate(ht_chaining.table):
    print(f"Slot {i}: {slot}")