# -*- coding: utf-8 -*-
"""Pertemuan pertama praktikum struktur data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QoHrsp-iPmvLiW-7p3nIUE5e2kR3Ykjx

MEMBUAT ARRAY
"""

import array as arr
a = arr.array('i',[1,2,3])
print("array lama: ", end=" ")
for i in range (0,3):
  print (a[i], end=" ")

b = arr.array ('d',[1.2, 2.3, 3.4])
print("\narray lama desimal:", end= " ")
for d in range (0,3):
  print (b[d], end=" ")

"""MENAMBAH ELEMEN ARRAY"""

import array as arr
a = arr.array('i',[1,2,3])
print("Array lama: ", end=" ")
for i in range (0,3):
  print (a[i], end=" ")

a.insert(1,4)
print("\nSetelah di tambah: ", end=" ")
for i in (a):
  print(i,end=" ")


#Desimal
b = arr.array ('d',[1.2, 2.3, 3.4])
print("\n\nArray lama desimal:", end= " ")
for d in range (0,3):
  print (b[d], end=" ")

b.append(2.4)
print("\nSetelah di tambah: ", end=" ")
for d in (b):
  print(d,end=" ")

"""MENGAKSES ELEMEN ARRAY"""

import array as arr
a = arr.array('i', [1,2,3,4,5,6])
print("Element ke: ", a[0])
print("Element ke: ", a[4])

b = arr.array('d', [1.2, 2.3, 3.4, 4.5])
print("\nElement ke: ", b[1])
print("Element ke: ", b[3])

"""MENGHAPUS ELEMENT ARRAY"""

import array
arr = array.array('i', [1,2,3,4,5,6])
print("Array baru: ", end=" ")
for i in range(0,5):
  print(arr[i], end=" ")

print("\nElement yang di hapus: ", end=" ")
print(arr.pop(3))
print("Setelah Element di hapus(pop): ", end=" ")
for i in range(0,5):
  print(arr[i], end=" ")

arr.remove(5)
print("\nSetelah element dihapus(remove): ", end=" ")
for i in range(0,4):
  print(arr[i], end=" ")

"""PEMOTONGAN ELEMENT ARRAY"""

import array as arr

l = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
a = arr.array('i', l)

print("Initial Array: ")
for i in (a):
    print(i, end=" ")

# Slicing dari indeks 3 sampai 8 (eksklusif)
Sliced_array = a[3:8]
print("\nSlicing elements in a range 3-8: ")
print(Sliced_array)

# Slicing dari indeks 5 sampai akhir
Sliced_array = a[5:]
print("\nElements sliced from 5th element till the end: ")
print(Sliced_array)

# Mencetak seluruh elemen dengan slicing
Sliced_array = a[:]
print("\nPrinting all elements using slice operation: ")
print(Sliced_array)

"""MENGUBAH ELEMENTT ARRAY"""

import array

arr = array.array('i', [1, 2, 3, 1, 2, 5])
print("Array before updation : ", end="")
for i in range(0, 6):
    print(arr[i], end=" ")
print("\r")

arr[2] = 6 # Mengubah elemen indeks 2 menjadi 6
print("Array after updation : ", end="")
for i in range(0, 6):
    print(arr[i], end=" ")
print()

arr[4] = 8 # Mengubah elemen indeks 4 menjadi 8
print("Array after updation : ", end="")
for i in range(0, 6):
    print(arr[i], end=" ")

"""BERBAGI OPERASI ARRAY"""

import array

arr = array.array('i', [1, 2, 3, 1, 2, 5])
print("Array before updation : ", end="")
for i in range(0, 6):
    print(arr[i], end=" ")
print("\r")

arr[2] = 6 # Mengubah elemen indeks 2 menjadi 6
print("Array after updation : ", end="")
for i in range(0, 6):
    print(arr[i], end=" ")
print()

arr[4] = 8 # Mengubah elemen indeks 4 menjadi 8
print("Array after updation : ", end="")
for i in range(0, 6):
    print(arr[i], end=" ")

"""OPERASI COUNT DAN REVERSE"""

import array

my_array = array.array('i', [1, 2, 3, 4, 2, 5, 2])

# Menghitung elemen array (berapa kali angka 2 muncul)
count = my_array.count(2)
print("Number of occurrences of 2:", count)

# Membalik Elemen Array
print("Original array:", *my_array)
my_array.reverse()
print("Reversed array:", *my_array)

"""EXTENDING ARRAY"""

import array as arr

# Extend Array Integer
a = arr.array('i', [1, 2, 3, 4, 5, 6])
print("The Before extend array is :", end=" ")
for i in range(0, 6):
    print(a[i], end=" ")
print()

a.extend([7, 8, 9, 10, 11, 12]) # Menambahkan list angka ke array a

print("\nThe After extend array is :", end=" ")
for i in range(0, 12):
    print(a[i], end=" ")
print()

# Extend Array Double
b = arr.array('d', [2.1, 2.2, 2.3, 2.4, 2.5, 2.6])
print("\nThe before extend array is :", end=" ")
for i in range(0, 6):
    print(b[i], end=" ")
print()

b.extend([2.6, 2.7, 2.8, 2.9]) # Menambahkan list desimal ke array b

print("\nThe after extend array is :", end=" ")
for i in range(0, 10): # Range disesuaikan dengan total elemen (6+4=10)
    print(b[i], end=" ")
print()