# -*- coding: utf-8 -*-
"""Praktikum Alpro Modul 5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qk_Og9IUBJ16xYuIg9ilfy5VyrXJxTr0

CODE PROGRAM SESUAI MODUL

Linear Search
"""

def LinierSearch(arr, N, x):
    for i in range(0, N):
        if (arr[i] == x):
            return i
    return -1

# Driver Code
if __name__ == "__main__": # Perhatikan penggunaan dua garis bawah (__)
    arr = [20, 10, 30, 50, 40]
    x = 10
    N = len(arr)

    # Function call
    result = LinierSearch(arr, N, x)
    if (result == -1):
        print("Element yang di cari tidak ada dalam array")
    else:
        print("Element yang di cari berada pada indeks ke-", result)

"""Binary Search"""

# It returns location of x in given array arr
def binarySearch(arr, l, r, x):
    while l <= r:
        mid = l + (r - l) // 2

        # Check if x is present at mid
        if arr[mid] == x:
            return mid

        # If x is greater, ignore left half
        elif arr[mid] < x:
            l = mid + 1

        # If x is smaller, ignore right half
        else:
            r = mid - 1

    # If we reach here, then the element was not present
    return -1

# Driver Code
if __name__ == "__main__":
    arr = [2, 5, 8, 12, 16, 23, 38, 56, 72, 91]
    x = 72

    # Function call
    result = binarySearch(arr, 0, len(arr)-1, x)
    if result != -1:
        print("Element is present at index", result)
    else:
        print("Element is not present in array")

"""Binary Search Dengan Rekursif"""

# Returns index of x in arr if present, else -1
def binarySearch(arr, l, r, x):
    # Check base case
    if r >= l:  # Gunakan huruf 'l' (left), bukan angka 1
        mid = l + (r - l) // 2

        # If element is present at the middle itself
        if arr[mid] == x:
            return mid

        # If element is smaller than mid, then it can only be present in left subarray
        elif arr[mid] > x:
            return binarySearch(arr, l, mid - 1, x)

        # Else the element can only be present in right subarray
        else:
            return binarySearch(arr, mid + 1, r, x)

    # Element is not present in the array
    else:
        return -1

# Driver Code
if __name__ == "__main__": # Gunakan double underscore __
    arr = [2, 5, 8, 12, 16, 23, 38, 56, 72, 91]
    x = 72

    # Function call
    result = binarySearch(arr, 0, len(arr)-1, x)
    if result != -1:
        print("Element terdapat pada indeks ke-", result)
    else:
        print("Element tidak ada dalam array")

"""Jump Search"""

import math

def jumpSearch(arr, x, n):
    # Finding block size to be jumped
    step = math.sqrt(n)

    # Finding the block where element is present (if it is present)
    prev = 0
    while arr[int(min(step, n)-1)] < x:
        prev = step
        step += math.sqrt(n)
        if prev >= n:
            return -1

    # Doing a Linear search for x in block beginning with prev.
    while arr[int(prev)] < x:
        prev += 1
        # If we reached next block or end of array, element is not present.
        if prev == min(step, n):
            return -1

    # If element is found
    if arr[int(prev)] == x:
        return prev

    return -1

# Driver code to test function
arr = [0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610]
x = 55
n = len(arr)

# Find the index of 'x' using Jump Search
index = jumpSearch(arr, x, n)

# Print the index where 'x' is located
print("Number", x, "is at index", "%.0f" % index)

"""Studi Kasus 1"""

# structure is used to return two values from minMax()
class pair:
    def _init_(self):
        self.min = 0
        self.max = 0

def getMinMax(arr: list, n: int) -> pair:
    minmax = pair()

    # If there is only one element then return it as min and max both
    if n == 1:
        minmax.max = arr[0]
        minmax.min = arr[0]
        return minmax

    # If there are more than one elements, then initialize min and max
    if arr[0] > arr[1]:
        minmax.max = arr[0]
        minmax.min = arr[1]
    else:
        minmax.max = arr[1]
        minmax.min = arr[0]

    for i in range(2, n):
        if arr[i] > minmax.max:
            minmax.max = arr[i]
        elif arr[i] < minmax.min:
            minmax.min = arr[i]

    return minmax

# Driver Code
if __name__ == "__main__":
    arr = [1000, 11, 445, 1, 330, 3000]
    arr_size = 6
    minmax = getMinMax(arr, arr_size)
    print("Minimum element is", minmax.min)
    print("Maximum element is", minmax.max)

"""Studi Kasus 2"""

def printTwoElements(arr):
    n = len(arr)
    temp = [0] * n # Creating temp array of size n with initial values as 0.
    repeatingNumber = -1
    missingNumber = -1

    for i in range(n):
        temp[arr[i] - 1] += 1
        if temp[arr[i] - 1] > 1:
            repeatingNumber = arr[i]

    for i in range(n):
        if temp[i] == 0:
            missingNumber = i + 1
            break

    print("The repeating number is", repeatingNumber, ".")
    print("The missing number is", missingNumber, ".")

# Driver Code
arr = [7, 3, 4, 5, 5, 6, 2]
printTwoElements(arr)