# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Ff0lO5aGXdu0Ak7sKKzhm0d3lFbLkbl

TREE
"""

# Struktur Tree berdasarkan identitas saya
#
#          19   <- root (jumlah huruf nama)
#         /  \
#        8    63  <- anak kiri: vokal | anak kanan: 2 digit NPM
#       /       \
#      1          9  <- DD=01 | MM=09

class Node:
    def __init__(self, data):
        self.data = data
        self.left = None
        self.right = None

# Membentuk tree secara manual
root = Node(19)           # jumlah huruf nama lengkap
root.left = Node(8)       # jumlah vokal pada nama
root.right = Node(63)     # dua digit terakhir NPM
root.left.left = Node(1)  # tanggal lahir (DD)
root.right.right = Node(9) # bulan lahir (MM)

# Fungsi inorder traversal
def inorder(node):
    if node:
        inorder(node.left)
        print(node.data, end=' ')
        inorder(node.right)

print('Inorder Traversal Tree Identitas:')
inorder(root)

# Program Binary Search Tree Identitas

class Node:
    def __init__(self, data):
        self.data = data
        self.left = None
        self.right = None

class BinarySearchTree:
    def __init__(self):
        self.root = None

    # Fungsi menyisipkan data sesuai aturan BST
    def insert(self, root, data):
        if root is None:
            return Node(data)
        if data < root.data:
            root.left = self.insert(root.left, data)
        else:
            root.right = self.insert(root.right, data)
        return root

# Fungsi-fungsi traversal
def inorder(node):
    if node:
        inorder(node.left)
        print(node.data, end=' ')
        inorder(node.right)

def preorder(node):
    if node:
        print(node.data, end=' ')
        preorder(node.left)
        preorder(node.right)

def postorder(node):
    if node:
        postorder(node.left)
        postorder(node.right)
        print(node.data, end=' ')

# Fungsi pencarian elemen dalam BST
def search(node, key):
    if node is None or node.data == key:
        return node
    if key < node.data:
        return search(node.left, key)
    return search(node.right, key)

# Inisialisasi dan penyisipan data
bst = BinarySearchTree()
root = None

# data_list berisi 7 angka dari identitas pribadi
# 63=3 digit NPM, 1=DD, 9=MM, 77=ASCII 'M', 85=ASCII 'U', 25 dan 42=bebas
data_list = [63, 1, 9, 77, 85, 25, 42]
for value in data_list:
    root = bst.insert(root, value)

# Menampilkan hasil traversal
print('Inorder Traversal  :', end=' ')
inorder(root)
print()
print('Preorder Traversal :', end=' ')
preorder(root)
print()
print('Postorder Traversal:', end=' ')
postorder(root)
print()

# Fitur pencarian
# Mencari dua digit terakhir NPM = 63
key1 = 63
res1 = search(root, key1)
print(f'Pencarian {key1}: {"Ditemukan" if res1 else "Tidak ditemukan"}')

# Mencari angka yang tidak ada dalam list
key2 = 100
res2 = search(root, key2)
print(f'Pencarian {key2}: {"Ditemukan" if res2 else "Tidak ditemukan"}')